# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171203_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='product/%Y/%m', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='product/%Y/%m', verbose_name='封面图片'),
        ),
    ]
