# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171213_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Style', verbose_name='产品样式'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=100, verbose_name='产品样式'),
        ),
    ]
