# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171214_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': '样式', 'verbose_name_plural': '样式'},
        ),
        migrations.AddField(
            model_name='style',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='样式描述'),
        ),
    ]
