# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171214_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='style',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
