# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
    ]
