# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPictureBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='banner/%Y/%m', verbose_name='产品图片背景')),
                ('url', models.URLField(blank=True, null=True, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '产品图片背景',
                'verbose_name_plural': '产品图片背景',
            },
        ),
        migrations.CreateModel(
            name='ProductStyleBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='banner/%Y/%m', verbose_name='产品样式背景')),
                ('url', models.URLField(blank=True, null=True, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '产品样式背景',
                'verbose_name_plural': '产品样式背景',
            },
        ),
    ]
