# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productpicturebanner_productstylebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpicturebanner',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='banner/%Y/%m', verbose_name='产品图片背景'),
        ),
        migrations.AlterField(
            model_name='productstylebanner',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='banner/%Y/%m', verbose_name='产品样式背景'),
        ),
    ]
