# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bg_image',
        ),
    ]
