# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20171222_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bg_image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='product/%Y/%m', verbose_name='样式背景图'),
        ),
    ]
