# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20171125_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m', verbose_name='封面图片'),
        ),
    ]
