# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Case',
        ),
    ]
