# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171203_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='blog/%Y/%m', verbose_name='封面图'),
        ),
    ]
