# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='author',
        ),
        migrations.RemoveField(
            model_name='introduce',
            name='image',
        ),
    ]
