# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_introduce_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduce',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='标题'),
        ),
    ]
