# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:18
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_introduce_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduce',
            name='contact',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='联系我们'),
        ),
        migrations.AddField(
            model_name='introduce',
            name='culture',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='企业文化'),
        ),
        migrations.AddField(
            model_name='introduce',
            name='idea',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='经营理念'),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='公司简介'),
        ),
    ]
