# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_case_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='关于我们背景')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '关于我们背景',
                'verbose_name_plural': '关于我们背景',
            },
        ),
        migrations.CreateModel(
            name='StoryBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='成功案例背景图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '成功案例背景图',
                'verbose_name_plural': '成功案例背景图',
            },
        ),
    ]
