# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogbanner_storybanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogBanner',
            new_name='IntroduceBanner',
        ),
    ]
