# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171214_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryBanner',
            new_name='NewsBanner',
        ),
    ]
