# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20171214_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsbanner',
            options={'verbose_name': '产品背景图', 'verbose_name_plural': '产品背景图'},
        ),
        migrations.AlterField(
            model_name='newsbanner',
            name='image',
            field=models.ImageField(upload_to='banner/%Y/%m', verbose_name='新闻背景图'),
        ),
    ]
