# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20171216_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsbanner',
            options={'verbose_name': '新闻背景图', 'verbose_name_plural': '新闻背景图'},
        ),
    ]
