# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171214_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebanner',
            name='index',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='casebanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='index',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
    ]
