# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171214_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexbanner',
            name='url',
        ),
    ]
