# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_indexbanner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbanner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='访问地址'),
        ),
    ]
