# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_indexbanner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebanner',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='banner/%Y/%m', verbose_name='案例轮播图'),
        ),
        migrations.AlterField(
            model_name='indexbanner',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='banner/%Y/%m', verbose_name='首页背景'),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='banner/%Y/%m', verbose_name='产品轮播图'),
        ),
    ]
